### ISSUE TITLE
Remote integration

### ISSUE THREAD

**Issue by chenglou** [chenglou/node-huxley#2]
Should be here: http://code.google.com/p/selenium/wiki/Grid2

**Comment by chenglou** [comment]
Meh, screw selenium =)

**Comment by parshap** [comment]
Screw Selenium indeed, but can you elaborate? Can't I already target a remote Selenium server by using the `--server` option?

**Comment by chenglou** [comment]
It's been a while, but I think I was thinking about something else when I opened the issue
