### ISSUE TITLE
Take only viewport screenshot

### ISSUE THREAD

**Issue by chenglou** [chenglou/node-huxley#36]
Selenium currently takes the whole page picture:
- Wasteful. Scrolling is implemented so no problem with capturing multiple screenshot by scrolling down.
- One randomly changing spot on the page can destroy the screenshot.
- Isn't coherent with the expectation of `screenSize` in Huxleyfile.

Selenium doesn't allow viewport screenshot. Will have to manually crop the picture. Do consider scrolling position.
The advantage of this method is that `screenSize` still works if it overflows smaller monitors , as the full page screenshot is taken first and cropped correctly anyways.

**Comment by donv** [comment]
@chenglou How is this feature used?  When I take screenshots using FireFox now, the whole page is saved, not just the visible viewport.

**Comment by chenglou** [comment]
Are you sure? I just tested this and it still works.
