### ISSUE TITLE
lodash dependency causing problems

### ISSUE THREAD

**Issue by esoman** [chenglou/node-huxley#81]
Could the dependency for lodash in package.json be changed to use a npm version instead of pointing to git?  It is causing conflicts with with other libraries that point to the npm version and rely on the directory structure in the npm module.

**Comment by chenglou** [comment]
@esoman humm I forgot why it pointed to that. Can you try it now?

**Comment by esoman** [comment]
Works great! Thanks for the quick turnaround.  One other thing, can I get an estimate on when this change will be published?

**Comment by chenglou** [comment]
Now =)
